spring:
  springdoc:
    swagger-ui:
      disable-swagger-default-url: true
      path: /myproject
  jpa:
    hibernate:
      show-sql: true
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://localhost:5432/flat_rent
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        orm:
          jdbc:
            bind: TRACE